export interface OrderItemStatus {
  id: string;
  name: string;
  status: string;
  checked: boolean;
  timestamp: string;
  category: string;
  delivered?: boolean;
  deliveredAt?: string;
  quantity?: number; // Added to track quantity per item split
  unitPrice?: number; // Added to track price per unit for historical accuracy
}

export type OrderOrigin = 'standard' | 'self_service_scale';
export type OperationalRoute = 'production' | 'bypass_production';
export type SelfServicePaymentMode = 'immediate' | 'deferred';

export interface SelfServiceFlowContext {
  orderOrigin?: OrderOrigin;
  operationalRoute?: OperationalRoute;
  servicePoint?: string | null;
  autoGeneratedComanda?: boolean;
  comandaOrigin?: OrderOrigin;
  paymentMode?: SelfServicePaymentMode;
  closedAtScale?: boolean;
}

export interface Order {
  id: string;
  client: string;
  mesa?: string;
  tableId?: string; // Link to actual table record
  waiterId?: string; // Assigned waiter
  comandaNumber: string;
  items: string[];
  itemsWithStatus: OrderItemStatus[];
  observations?: string;
  status: string; // 'montagem' | 'churrasqueira' | 'pronto' | 'delivered' | 'cancelada';
  timestamp: string;
  createdAt: string;
  horarioCriacao: string;
  dateKey: string;
  timeInChurrasqueira?: string | null;
  timeInMontagem?: string | null;
  timeInProntos?: string | null;
  deliveredAt?: string | null;
  totalPrice: number;
  isPago: boolean;
  createdBy: string;
  createdByName: string;
  orderOrigin?: OrderOrigin;
  operationalRoute?: OperationalRoute;
  servicePoint?: string | null;
  autoGeneratedComanda?: boolean;
  priceMap?: Record<string, number>;
  [key: string]: any;
}

export interface Caixa {
  id: string;
  data: string;
  status: 'aberto' | 'fechado';
  abertoPor: string;
  abertoPorNome: string;
  abertoAt?: any; // Timestamp
  valorInicial: number;
  vendasTotal: number;
  reforcosTotal: number;
  sangriasTotal: number;
  saldoEsperado: number;
  saldoReal?: number;
  diferenca?: number;
  movimentosCount: number;
  fechadoAt?: any; // Firestore Timestamp
  fechadoPor?: string;
  fechadoPorNome?: string;
  ticketMedio?: number;
  atualizado?: any;
  porForma?: {
    dinheiro: number;
    pix: number;
    debito: number;
    credito: number;
    [key: string]: number;
  };
}

export interface Ingredient {
  id: string;
  nome: string;
  qt: number;
  un: string;
}

export interface PizzaSize {
  name: string;
  maxFlavors: number;
  active?: boolean;
}

export interface PizzaConfig {
  sizes: PizzaSize[];
  pricingMode?: 'HIGHER' | 'AVERAGE';
}

export interface Product {
  id: string;
  name: string;
  price?: number;
  category: string;
  subcategory?: string; // Dynamic pizza subcategory from company settings
  active: boolean;
  createdAt: number;
  description?: string;
  image?: string;
  image_url?: string;
  prices?: Record<string, number>;
  ingredients?: string[]; // Para pizza
  customIngredients?: string; // Para pizza
  accompaniments?: string[]; // Acompanhamentos de espetinho
  inventoryItems?: Ingredient[];
  [key: string]: any;
}

export interface Cardapio {
  caldos: Product[];
  comidas: Product[];
  bebidas: Product[];
  espetinhos: Product[];
  espetinhosSimples?: Product[];
  espetinhosEspeciais?: Product[];
  outros?: Product[];
  porcoes?: Product[];
  pizzas?: Product[];
  [key: string]: Product[] | undefined;
}

export interface Funcionario {
  id: string;
  uid?: string;
  nome: string;
  email: string;
  cpf: string;
  funcao: 'admin' | 'churrasqueiro' | 'montagem' | 'garcom' | string;
  companyId?: string;
  ativo: boolean;
  criadoEm?: string;
  desativadoEm?: string;
  atualizadoEm?: string;
  [key: string]: any;
}

export interface Comanda {
  id: string;
  dateKey: string;
  comandaNumber: string;
  status: 'aberta' | 'fechada' | 'cancelada' | 'paga' | 'merged';
  mesa?: string;
  cliente?: string;
  totalConsumido: number;
  totalPago: number;
  saldoAberto: number;
  recebidoPor?: string[];
  abertaAt: any; // Timestamp
  criadaEm: string;
  horarioCriacao: string;
  abertaPor: string;
  abertaPorNome: string;
  comandaOrigin?: OrderOrigin;
  paymentMode?: SelfServicePaymentMode;
  closedAtScale?: boolean;
  fechadaAt?: any; // Timestamp
  fechadaPor?: string;
  fechadaPorNome?: string;
  canceladaEm?: string; // ISO String
  canceladaPor?: string;
  canceladaPorNome?: string;
  motivoCancelamento?: string;
  atualizado?: any; // Timestamp
  [key: string]: any;
}

export interface Environment {
  id: string;
  company_id: string;
  name: string;
  section_order: number;
  created_at?: string;
}

export interface Table {
  id: string;
  company_id: string;
  environment_id: string | null;
  number: string;
  seats: number;
  position_x: number;
  position_y: number;
  shape: 'round' | 'square' | 'rect';
  width: number;
  height: number;
  rotation: number;
  active: boolean;
  created_at?: string;
  // Extended properties for UI (not in DB)
  status?: 'Livre' | 'Ocupada' | 'Pagamento' | 'Reservada';
  order_total?: number;
  order_time?: string;
  current_order_id?: string;
  waiter_name?: string;
}
