#!/usr/bin/env node
/**
 * Figma Code Connect Sync
 *
 * Automates repetitive setup steps across app/web/site:
 * 1) Sync FIGMA_TOKEN + FIGMA_FILE_KEY to .env.local files
 * 2) Replace FIGMA_FILE_KEY placeholder in all *.figma.ts URLs
 * 3) Optionally apply node-id mapping from JSON
 * 4) Optionally run npm figma:parse in all projects
 *
 * Usage:
 *   node scripts/figma-sync.mjs --file-key <FIGMA_FILE_KEY>
 *   node scripts/figma-sync.mjs --file-key <KEY> --token <FIGMA_TOKEN>
 *   node scripts/figma-sync.mjs --file-key <KEY> --node-map docs/design-system/figma-node-map.json
 *   node scripts/figma-sync.mjs --file-key <KEY> --skip-parse
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { spawnSync } from 'child_process';

const root = process.cwd();
const projects = ['restaurante-app', 'restaurante-web', 'restaurante-site'];

function parseArgs(argv) {
  const args = {
    fileKey: '',
    token: '',
    nodeMap: '',
    runParse: true,
    help: false,
  };

  for (let i = 0; i < argv.length; i += 1) {
    const current = argv[i];
    if (current === '--help' || current === '-h') args.help = true;
    else if (current === '--skip-parse') args.runParse = false;
    else if (current === '--file-key') args.fileKey = argv[i + 1] || '';
    else if (current.startsWith('--file-key=')) args.fileKey = current.split('=')[1] || '';
    else if (current === '--token') args.token = argv[i + 1] || '';
    else if (current.startsWith('--token=')) args.token = current.split('=')[1] || '';
    else if (current === '--node-map') args.nodeMap = argv[i + 1] || '';
    else if (current.startsWith('--node-map=')) args.nodeMap = current.split('=')[1] || '';
  }

  return args;
}

function usage() {
  console.log('Usage:');
  console.log('  node scripts/figma-sync.mjs --file-key <FIGMA_FILE_KEY>');
  console.log('  node scripts/figma-sync.mjs --file-key <KEY> --token <FIGMA_TOKEN>');
  console.log('  node scripts/figma-sync.mjs --file-key <KEY> --node-map docs/design-system/figma-node-map.json');
  console.log('  node scripts/figma-sync.mjs --file-key <KEY> --skip-parse');
}

function isLikelyFigmaToken(value) {
  return typeof value === 'string' && /^figd_[A-Za-z0-9_-]{10,}$/.test(value);
}

function readEnvValue(envPath, key) {
  if (!existsSync(envPath)) return '';
  const content = readFileSync(envPath, 'utf8');
  const re = new RegExp(`^${key}=(.*)$`, 'm');
  const match = content.match(re);
  return match ? match[1].trim() : '';
}

function upsertEnvValue(content, key, value) {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`^${escaped}=.*$`, 'm');
  if (re.test(content)) return content.replace(re, `${key}=${value}`);
  const suffix = content.endsWith('\n') ? '' : '\n';
  return `${content}${suffix}${key}=${value}\n`;
}

function ensureEnvLocal(project, token, fileKey) {
  const envPath = join(root, project, '.env.local');
  const examplePath = join(root, project, '.env.example');

  let content = '';
  if (existsSync(envPath)) {
    content = readFileSync(envPath, 'utf8');
  } else if (existsSync(examplePath)) {
    content = `${readFileSync(examplePath, 'utf8')}\n`;
  } else {
    content = '# Auto-generated by scripts/figma-sync.mjs\n';
  }

  if (token) content = upsertEnvValue(content, 'FIGMA_TOKEN', token);
  if (fileKey) content = upsertEnvValue(content, 'FIGMA_FILE_KEY', fileKey);

  writeFileSync(envPath, content, 'utf8');
  return envPath;
}

function loadNodeMap(nodeMapPath) {
  if (!nodeMapPath) return {};
  const fullPath = join(root, nodeMapPath);
  if (!existsSync(fullPath)) {
    throw new Error(`Node map not found: ${nodeMapPath}`);
  }
  const parsed = JSON.parse(readFileSync(fullPath, 'utf8'));
  return parsed.nodes || {};
}

function updateCodeConnectFile(filePath, fileKey, mappedNodeId = '') {
  const fullPath = join(root, filePath);
  if (!existsSync(fullPath)) return false;

  const original = readFileSync(fullPath, 'utf8');
  let updated = original;

  // Replace placeholder token if present.
  if (fileKey) {
    updated = updated.replace(/\{FIGMA_FILE_KEY\}/g, fileKey);
    // Also normalize concrete old keys to current key.
    updated = updated.replace(
      /https:\/\/figma\.com\/design\/[^/]+\/RestaurantOS-Design-System\?node-id=/g,
      `https://figma.com/design/${fileKey}/RestaurantOS-Design-System?node-id=`
    );
  }

  // Apply node-id mapping when provided.
  if (mappedNodeId) {
    updated = updated.replace(/node-id=[^'"\s)]+/g, `node-id=${mappedNodeId}`);
  }

  if (updated !== original) {
    writeFileSync(fullPath, updated, 'utf8');
    return true;
  }

  return false;
}

function runParse(project) {
  const result = spawnSync('npm', ['run', 'figma:parse'], {
    cwd: join(root, project),
    stdio: 'inherit',
    shell: true,
  });
  return result.status === 0;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    usage();
    process.exit(0);
  }

  const webEnvPath = join(root, 'restaurante-web', '.env.local');
  const fallbackToken = readEnvValue(webEnvPath, 'FIGMA_TOKEN');
  const fallbackFileKey = readEnvValue(webEnvPath, 'FIGMA_FILE_KEY');

  const fileKey = args.fileKey || fallbackFileKey;
  const token = args.token || fallbackToken;

  if (!fileKey) {
    console.error('ERROR: FIGMA_FILE_KEY missing. Use --file-key <KEY> or set FIGMA_FILE_KEY in restaurante-web/.env.local');
    process.exit(1);
  }

  if (args.token && !isLikelyFigmaToken(args.token)) {
    console.error('ERROR: invalid --token value. Expected a token starting with "figd_".');
    console.error('Hint: do not pass FIGMA_FILE_KEY to --token.');
    process.exit(1);
  }

  const nodeMap = loadNodeMap(args.nodeMap);

  console.log('============================================');
  console.log(' Figma Sync');
  console.log('============================================');
  console.log(`File key: ${fileKey}`);
  console.log(`Token: ${token ? 'present' : 'missing (will not be propagated)'}`);
  console.log(`Node map: ${args.nodeMap ? args.nodeMap : 'none'}`);
  console.log('');

  for (const project of projects) {
    const envPath = ensureEnvLocal(project, token, fileKey);
    console.log(`env synced: ${envPath}`);
  }

  const figmaFiles = [
    'restaurante-app/src/ui/Button.figma.tsx',
    'restaurante-app/src/ui/Card.figma.tsx',
    'restaurante-app/src/ui/Badge.figma.tsx',
    'restaurante-app/src/ui/FormInput.figma.tsx',
    'restaurante-app/src/ui/ProductCard.figma.tsx',
    'restaurante-web/src/ui/Button.figma.tsx',
    'restaurante-web/src/ui/Card.figma.tsx',
    'restaurante-web/src/ui/Badge.figma.tsx',
    'restaurante-web/src/ui/FormInput.figma.tsx',
    'restaurante-web/src/ui/ProductCard.figma.tsx',
    'restaurante-site/src/components/Button.figma.tsx',
    'restaurante-site/src/components/Card.figma.tsx',
  ];

  let changedCount = 0;
  for (const file of figmaFiles) {
    const changed = updateCodeConnectFile(file, fileKey, nodeMap[file] || '');
    if (changed) changedCount += 1;
  }
  console.log(`code-connect files updated: ${changedCount}/${figmaFiles.length}`);

  if (args.runParse) {
    console.log('');
    console.log('Running figma:parse in all projects...');
    const results = projects.map((project) => ({ project, ok: runParse(project) }));
    const failed = results.filter((r) => !r.ok);
    console.log('');
    console.log('Parse summary:');
    for (const row of results) {
      console.log(`- ${row.project}: ${row.ok ? 'OK' : 'FAILED'}`);
    }
    if (failed.length > 0) process.exit(1);
  }

  console.log('');
  console.log('Done.');
}

main();
