
auth.token=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

defaults.org=machado-cunha-soft-house
defaults.project=restaurante-app

defaults.url=https://sentry.io/
